name: Spirits
version: 0.1.6
author: Allymonies
main: com.omnipico.spirits.Spirits
api-version: 1.16
website: omnipico.com
softdepend: [Vault]
depend: [ProtocolLib]
commands:
  spirits:
    description: Base command for Spirits
    usage: /spirits
    permission: spirits.spirits
permissions:
  spirits.spirits:
    default: true
    description: Allows usage of /spirits
  spirits.setlives:
    default: op
    description: Allows usage of /spirits setlives
  spirits.revive.*:
    default: op
    description: Allows usage of /spirits revive
    children:
      spirits.revive: true
      spirits.revive.others: true
  spirits.kill.*:
    default: op
    description: Allows usage of /spirits kill
    children:
      spirits.kill: true
      spirits.kill.others: true
  spirits.hardcore.*:
      default: op
      description: Allows usage of /spirits kill
      children:
        spirits.hardcore: true
        spirits.hardcore.others: true
  spirits.*:
    default: op
    description: Allows access to every Spirits command.
    children:
      spirits.spirits: true
      spirits.setlives: true
      spirits.revive: true
      spirits.kill: true
      spirits.hardcore: true
