name: Spirits
version: 0.0.1
author: Allymonies
main: com.omnipico.spirits.Spirits
api-version: 1.16
website: omnipico.com
softdepend: [Vault]
depend: [ProtocolLib]
commands:
  spirits:
    description: Base command for Spirits
    usage: /spirits
    permission: spirits.spirits
permissions:
  spirits.spirits:
    default: true
    description: Allows usage of /spirits
  spirits.setlives:
    default: op
    description: Allows usage of /spirits setlives
  spirits.revive:
    default: op
    description: Allows usage of /spirits revive
  spirits.kill:
    default: op
    description: Allows usage of /spirits kill
  spirits.*:
    default: op
    description: Allows access to every Spirits command.
    children:
      spirits.spirits: true
